const SOUZAS = [
  { file: "original.jpeg", author: "matheusaudibert", authorId: 85813476 },
  { file: "sounic.png", author: "matheusaudibert", authorId: 85813476 },
  { file: "souza-argentino.jpg", author: "matheusaudibert", authorId: 85813476 },
  { file: "souza-buzz.jpg", author: "matheusaudibert", authorId: 85813476 },
  { file: "souza-careca.png", author: "matheusaudibert", authorId: 85813476 },
  { file: "souza-grande.png", author: "matheusaudibert", authorId: 85813476 },
  { file: "souza-kawaii.jpg", author: "matheusaudibert", authorId: 85813476 },
  { file: "souza-megabrain.png", author: "matheusaudibert", authorId: 85813476 },
  { file: "souza-minions.jpg", author: "matheusaudibert", authorId: 85813476 },
  { file: "souza-negro.png", author: "matheusaudibert", authorId: 85813476 },
  { file: "souza-palhaco.png", author: "matheusaudibert", authorId: 85813476 },
  { file: "souza-saiyajin.png", author: "matheusaudibert", authorId: 85813476 },
  { file: "souza-inter.png", author: "matheusaudibert", authorId: 85813476 },
];
